export const characterSlots = [
  {
    id: "lead",
    label: "Lead Dancer",
    url: "/assets/characters/Slow Jog Backwards.fbx",
    position: [-3.1, 0.42, 0],
    rotationY: 0.35,
    animationSet: "embeddedHumanoid",
    scaleMultiplier: 1.0,
    targetHeight: 5.05,
    placeholderScale: 0.88,
    offsetX: 0,
    offsetY: 0,
    offsetZ: 0,
    accent: "#80b8ff",
  },
  {
    id: "partner",
    label: "Partner Dancer",
    url: "/assets/characters/Capoeira.fbx",
    position: [3.1, 0.42, 0],
    rotationY: -0.35,
    animationSet: "embeddedHumanoid",
    scaleMultiplier: 1.0,
    targetHeight: 4.9,
    placeholderScale: 0.88,
    offsetX: 0,
    offsetY: 0,
    offsetZ: 0,
    accent: "#ff9ed6",
  },
];
